config/routes.rb
Rails.application.routes.draw do
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = MarketsFacade.get_all_markets
  end

  def show
    @market = MarketsFacade.get_a_market(params[:id])
    @market_address = MarketsFacade.readable_address(params[:id])
    @vendors = MarketsFacade.get_all_vendors_for_market(params[:id])
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = VendorsFacade.get_a_vendor(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "markets" %>
    <%= stylesheet_link_tag "vendors" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <style type="text/css">
      @font-face {
        font-family: 'Poppins Regular';
        src: font-url('Poppins-Regular.ttf') format('truetype'); 
        font-weight: normal;
        font-style: normal;
      }

      body {
        font-family: 'Poppins Regular';
      }
    </style>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<div class="markets-index">
  <h1 class="page-title">Markets</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>State</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @markets.each do |market| %>
        <tr id="market_<%= market.id %>">
          <td><%= market.name %></td>
          <td><%= market.city %></td>
          <td><%= market.state %></td>
          <td><%= button_to "View Details", market_path(market.id), method: :get %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/markets/show.html.erb
<div class="markets-show"> 
  <div class="market-details">
    <h1 class="market-name"><%= @market.name %></h1>
    <p class="market-address"><%= @market_address %></p>

    <h2 class="vendors-heading">Vendors at our Market:</h2>
    <ul class="vendor-list">
      <% @vendors.each do |vendor| %>
        <li class="vendor-list-item">
          <%= link_to vendor.name, vendor_path(vendor.id) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/vendors/show.html.erb
<div class="vendor-show">
  <h1 class="vendor-name"><%= @vendor.name %></h1>
  <div class="vendor-info">
    <p class="label"><strong>Contact Info:</strong></p>
    <p class="vendor-contact-name"><strong>name:</strong> <%= @vendor.contact_name %></p>
    <p class="vendor-phone"><strong>phone:</strong> <%= @vendor.contact_phone %></p>
    <p class="label"><strong>Credit Accepted?</strong></p>
    <p class="accepts-credit <%= @vendor.credit_accepted ? 'green' : 'red' %>">
      <%= @vendor.credit_accepted ? "Yes" : "No" %>
    </p>
    <p class="label"><strong>Description:</strong></p>
    <p class="description"><%= @vendor.description %></p>
  </div>
</div>